title: My blog
author: Axel Lárusson
email: axelminn@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  This is a blog for Axel Lárusson for the course DH2650, KTH.
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: thelehhman/texture
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Axel Lárusson
  tagline: Software Developer
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    # twitter: thelehhman
    github:  axelminn
    linkedIn: in/axellarusson
    # facebook: axel.larusson
    # mail: axelminn@gmail.com
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed